[versions]
    accompanist = '0.24.7-alpha'
    coil = "2.0.0-rc03"
    compose = "1.2.0-alpha08"
    exoplayer = "2.17.1"
    lumberjack = "5.2.5"
    okhttp = "4.9.3"
    retrofit = "2.9.0"
    sqldelight = "1.5.3"

[libraries]
accompanist-insets = { module = 'com.google.accompanist:accompanist-insets-ui', version.ref = "accompanist" }
accompanist-navigation = { module = 'com.google.accompanist:accompanist-navigation-animation', version.ref = "accompanist" }
accompanist-permissions = { module = 'com.google.accompanist:accompanist-permissions', version.ref = "accompanist" }
accompanist-swiperefresh = { module = 'com.google.accompanist:accompanist-swiperefresh', version.ref = "accompanist" }
accompanist-systemui = { module = 'com.google.accompanist:accompanist-systemuicontroller', version.ref = "accompanist" }
accompanist-webview = { module = 'com.google.accompanist:accompanist-webview', version.ref = "accompanist" }
androidx-activity = 'androidx.activity:activity-compose:1.6.0-alpha01'
androidx-compose-foundation = { module = 'androidx.compose.foundation:foundation', version.ref = "compose" }
androidx-compose-foundation-layout = { module = 'androidx.compose.foundation:foundation-layout', version.ref = "compose" }
androidx-compose-hilt-navigation = 'androidx.hilt:hilt-navigation-compose:1.0.0'
androidx-compose-livedata = { module = 'androidx.compose.runtime:runtime-livedata', version.ref = "compose" }
androidx-compose-material = { module = 'androidx.compose.material:material', version.ref = "compose" }
androidx-compose-navigation = 'androidx.navigation:navigation-compose:2.5.0-beta01'
androidx-compose-tooling = { module = 'androidx.compose.ui:ui-tooling-preview', version.ref = "compose" }
androidx-compose-ui = { module = 'androidx.compose.ui:ui', version.ref = "compose" }
androidx-compose-ui-util = { module = 'androidx.compose.ui:ui-util', version.ref = "compose" }
androidx-core = 'androidx.core:core-ktx:1.9.0-alpha02'
androidx-datastore-preferences = 'androidx.datastore:datastore-preferences:1.0.0'
androidx-lifecycle = 'androidx.lifecycle:lifecycle-runtime-ktx:2.5.0-beta01'
androidx-preference = 'androidx.preference:preference-ktx:1.2.0'
androidx-window = 'androidx.window:window:1.1.0-alpha01'
androidx-work = 'androidx.work:work-runtime-ktx:2.8.0-alpha02'
androidx-work-hilt = 'androidx.hilt:hilt-work:1.0.0'
coil-base = { module = 'io.coil-kt:coil-base', version.ref = "coil" }
coil-compose = { module = 'io.coil-kt:coil-compose', version.ref = "coil" }
coil-gif = { module = 'io.coil-kt:coil-gif', version.ref = "coil" }
coil-video = { module = 'io.coil-kt:coil-video', version.ref = "coil" }
exif = "androidx.exifinterface:exifinterface:1.3.3"
exoplayer-base = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
exoplayer-okhttp = { module = "com.google.android.exoplayer:extension-okhttp", version.ref = "exoplayer" }
flowpreferences = 'com.fredporciuncula:flow-preferences:1.6.0'
hilt = 'com.google.dagger:hilt-android:2.41'
infobar = 'com.radusalagean:info-bar-compose:1.0.0'
jwt = 'com.auth0.android:jwtdecode:2.0.1'
kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.1"
lumberjack-core = { module = "com.github.MFlisar.Lumberjack:lumberjack-library", version.ref = "lumberjack" }
lumberjack-file = { module = "com.github.MFlisar.Lumberjack:lumberjack-filelogger", version.ref = "lumberjack" }
lumberjack-feedback = { module = "com.github.MFlisar.Lumberjack:lumberjack-feedback", version.ref = "lumberjack" }
lumberjack-feedback-manager = "com.github.MFlisar:FeedbackManager:1.3"
lumberjack-notification = { module = "com.github.MFlisar.Lumberjack:lumberjack-notification", version.ref = "lumberjack" }
logger = 'com.jakewharton.timber:timber:4.7.1'
maps = 'com.google.android.gms:play-services-maps:18.0.2'
maps-compose = 'com.google.maps.android:maps-compose:2.1.0'
maps-utils = 'com.google.maps.android:android-maps-utils:2.3.0'
maps-utils-ktx = 'com.google.maps.android:maps-utils-ktx:3.4.0'
moshi = 'com.squareup.moshi:moshi-kotlin:1.13.0'
okhttp = { module = 'com.squareup.okhttp3:okhttp', version.ref = "okhttp" }
okhttp-logging = { module = 'com.squareup.okhttp3:logging-interceptor', version.ref = "okhttp" }
okhttp-url = { module = 'com.squareup.okhttp3:okhttp-urlconnection', version.ref = "okhttp" }
retrofit-core = { module = 'com.squareup.retrofit2:retrofit', version.ref = "retrofit" }
retrofit-moshi = { module = 'com.squareup.retrofit2:converter-moshi', version.ref = "retrofit" }
result = "com.michael-bull.kotlin-result:kotlin-result:1.1.16"
sqldelight-android = { module = 'com.squareup.sqldelight:android-driver', version.ref = "sqldelight" }
sqldelight-coroutines = { module = 'com.squareup.sqldelight:coroutines-extensions', version.ref = "sqldelight" }
urlvalidator = "commons-validator:commons-validator:1.7"

[bundles]
lumberjack = ["lumberjack-core", "lumberjack-file", "lumberjack-feedback", "lumberjack-notification", "lumberjack-feedback-manager"]