name: Build main branch and PRs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create local properties
      run: echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" > local.properties
    - name: Copy mock google services
      run: cp mock-google-services.json app/google-services.json
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Archive apk
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: |
          app/build/outputs/apk/debug
