name: Build release

on:
  push:
    tags:
      - v**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create local properties
      run: echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" > local.properties
    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.KEYSTORE }}
      run: |
        mkdir "keystore"
        echo $ENCODED_STRING | base64 -di > "keystore/keystore.jks

    - name: Build with Gradle
      run: ./gradlew app:bundleRelease
      env:
        KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
        KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
    - name: Archive release bundle
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: workspace
        path: |
          .
