name: Build release

on:
  push:
    tags:
      - v**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create local properties
      run: touch local.properties
    - name: Create maps api key
      run: echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" > secrets.properties
    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.KEYSTORE }}
      run: |
        mkdir app/keystore
        echo $ENCODED_STRING | base64 -di > app/keystore/keystore.jks
    - name: Decode Google Services json
      env:
        ENCODED_STRING: ${{ secrets.GOOGLE_SERVICES }}
      run: |
        echo $ENCODED_STRING | base64 -di > app/google-services.json
    - name: Build with Gradle
      run: ./gradlew app:bundleRelease
      env:
        KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
        KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
    - name: Archive release bundle
      uses: actions/upload-artifact@v3
      with:
        name: bundle
        path: |
          app/build/outputs/bundle/release
