name: Versions check
on:
  schedule:
      - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run version check
        run: ./gradlew versionCatalogUpdate
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.0