name: Versions check
on:
  schedule:
      - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run version check
        run: ./gradlew versionCatalogUpdate